### PR TITLE
updated histpy version

### PR DESCRIPTION
**Pull request by ckarwin**
updated histpy version to 1.0.2. I tried updating to: histpy @ git+https://gitlab.com/burstcube/histpy.git@develop, but it seems that the .plot() method has been replaced with .draw(). @israelmcmc Is this true?

### CODE REVIEW

**Comment by israelmcmc** [comment]
Hmm nope, plot is still in there. You can also use draw, but that was the case almost from the beginning, for backward compatibility. What error are you getting?

**Comment by ckarwin** [comment]
@israelmcmc Yeah after posting my last comment I went and looked at the histpy code and saw that it's still there. Rhea is trying to run the atmosphere notebook and when she tries to make the diagnostic plots she gets the error: 'Histogram' object has no attribute 'plot'. I've run a number of tests, including installing the repo in a fresh environment, but so far I'm unable to reproduce the error. So I'm not sure what is going on there.

**Comment by israelmcmc** [comment]
Most likely Python is picking up an old version that didn't have plot(), only draw(), instead of develop

**Comment by ckarwin** [comment]
Yes, I was thinking the same thing.

**Pull request merged**
